services:
  service-1:
    container_name: service-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8881:8888
    environment:
      RPC_PORT: 8888
      SERF_PORT: 8080
      BIND_ADDR: :8080
      START_JOIN_ADDRS: service-2:8080,service-3:8080
    restart: always
    volumes:
      - ../:/app
  service-2:
    container_name: service-2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8882:8888
    environment:
      RPC_PORT: 8888
      SERF_PORT: 8080
      BIND_ADDR: :8080
      START_JOIN_ADDRS: service-1:8080,service-3:8080
    restart: always
    volumes:
      - ../:/app
  service-3:
    container_name: service-3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8883:8888
    environment:
      RPC_PORT: 8888
      SERF_PORT: 8080
      BIND_ADDR: :8080
      START_JOIN_ADDRS: service-1:8080,service-2:8080
    restart: always
    volumes:
      - ../:/app
